### ISSUE TITLE
Charmap code can't decode byte

### ISSUE THREAD

**Issue by varshini-prakash** [akshaychawla/ImageNet-downloader#4]
Traceback (most recent call last):
  File "download_images.py", line 18, in <module>
    urls = f.readlines()
  File "C:\Users\Mahathi\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3779: character maps to <undefined>

**Comment by akshaychawla** [comment]
Hi @terminator-007 

I think this is happening because you might be using Python3 instead of Python2. Can you check if it works with Python 3 ? 

I'll try to make my code py2/py3 compliant in the meantime :smiley:
